# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# ----- Build Stage -----
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy dependency and config files first to leverage cache
COPY package.json package-lock.json tsconfig.json ./

# Install build dependencies for native modules (keytar)
RUN apk add --no-cache python3 make g++ libsecret-dev

# Install all dependencies (including dev) for build
# Use --ignore-scripts then rebuild to compile native modules without running prepare
RUN npm install --ignore-scripts && npm rebuild

# Copy source code and other necessary files
# Copy source code and other necessary files
COPY index.ts smithery.yaml ./
COPY llms.txt llms-full.txt ./

# Build the project
# 1. Compile TS to JS (dist/)
# 2. Build Smithery HTTP adapter (.smithery/)
RUN npm run build:stdio && npm run build:http

# ----- Production Stage -----
FROM node:lts-alpine AS production
LABEL maintainer="Nekzus <nekzus.dev@gmail.com>"
LABEL description="NPM Sentinel MCP Server for package analysis"
LABEL version="1.16.2"
WORKDIR /app

# Copy only the necessary artifacts from the build
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.smithery ./.smithery
COPY --from=builder /app/llms.txt /app/llms-full.txt ./

# Install only production dependencies
RUN npm install --omit=dev --ignore-scripts && npm cache clean --force

# Use non-root user for security
USER node

# Expose the standard port (adjust if you use another)
EXPOSE 3000

# Optional HEALTHCHECK (uncomment and adjust the endpoint if you have one)


# Startup command (Run the Smithery HTTP adapter)
CMD ["node", ".smithery/index.cjs"] 